### ISSUE TITLE
Comparison to Cquery

### ISSUE THREAD

**Issue by nealot** [MaskRay/emacs-ccls#1]
What are some of the main highlights of emacs-ccls which seperate it from cquery? What reason is there to switch from cquery to this package?

**Comment by MaskRay** [comment]
emacs-ccls does not provide more features than emacs-cquery. But the server side code uses `$ccls/` prefixed messages so a separate Emacs package is required.

The mere noticeable difference is how project roots are located. `ccls-project-root-matchers`

**Comment by MaskRay** [comment]
I disagree on many designs of cquery with its original author. I felt constrained when I was developing cquery, by forking, I can focus on satisfying my own needs and in the meantime make it benefit others. It will have much opinionated stuff, including:

* `-std=c++1z` (c++17), while I have upgraded `-std=c++11` to `-std=c++14` in cquery.
* Switch to Clang C++ API someday. It will be hard for them to switch because releases.llvm.org Windows releases do not include C++ header files.
* Probably unnoticeable improvement in workspace/symbol textDocument/definition
*

**Comment by nealot** [comment]
Thanks for your response! You've convinced me to switch from cquery to ccls and so far it has been pleasant. It would be quite nice to add some of these points to the main ccls README just for posterity -- I'm sure others might have the same question.

**Comment by MaskRay** [comment]
Written a bit in README.md. I am curious how you find this project because I haven't advertised it yet. Becoming famous is two-edged to me. It does make one delighted as their work is recognized by others but addressing issues and (arguably sometimes improper) pull requests also lays maintenance burden.

**Comment by Compro-Prasad** [comment]
A bit doesn't help. People like full explanation.

**Comment by germandiagogomez** [comment]
Besides all the "I do not like" things, is there any objective measure by which emacs would not work correctly with cquery? As a user, for me this is about features, not about design disagreements. 

- What works better in ccls that works wrong in cquery? What improvements could I get from there? Forking is ok and is a personal decision, but that creates a fork in the effort for a tool that does very similar things and creates different bugs in different packets that could be fixed just in one.

**Comment by MaskRay** [comment]
@germandiagogomez 

See notes in https://github.com/MaskRay/ccls/releases . Many of them are not available in cquery.
